# <font color = red> Numpy

In [1]:
import numpy as np
import warnings
warnings.filterwarnings("ignore")

---
## <font color = blue> Create a Numpy array</font>
---
    
### 1.1 Using `np.array()`

In [2]:
# Create a numpy array

np_arr = np.array([[11,23,32],[12,34,56],[77,77,54]])
print(np_arr)
print()
print(np_arr.shape)

[[11 23 32]
 [12 34 56]
 [77 77 54]]

(3, 3)

In [3]:
np_arr = np.array([[11,23,32],[12,34,56],[77,77]])
print(np_arr)
print()
print(np_arr.shape)

[list([11, 23, 32]) list([12, 34, 56]) list([77, 77])]

(3,)

In [4]:
np_arr = np.array([[11,23,32],[12,34,56],[77,77,None]])
print(np_arr)
print()
print(np_arr.shape)

[[11 23 32]
 [12 34 56]
 [77 77 None]]

(3, 3)

### 1.2 `np.zeros() and np.ones()`

In [17]:
np_zeros = np.zeros([2,4])
np_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np_ones = np.ones([2,4])
np_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### 1.3 `np.full()`

In [19]:
np.full((3,2),4)

array([[4, 4],
       [4, 4],
       [4, 4]])

### 1.4 `np.arange()`

In [20]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### 1.5 `np.linspace()`

the `linspace()` function generates an array with evenly spaced values between specified start, end values, using a specified number of elements

In [22]:
np.linspace(0, 1, 5)

array([0., 0., 0., 1., 1.])

In [23]:
np.linspace(0, 1, 20)
# 20 points equally spaced between 0 and 1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [24]:
np.linspace(0, 1, 20, False)
# 20 points equally spaced between 0 and 1, not including 1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

### 1.6 `identity`

In [25]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 1.7 `np.random()`

In [26]:
np.random.random(size=2)
# Return random floats in the half-open interval [0.0, 1.0).
# Results are from the “continuous uniform” distribution over the stated interval.

array([0., 1.])

In [27]:
np.random.normal(size=2)
# creates an array of specified shape and fills it with random values which 
# is actually a part of Normal(Gaussian)Distribution. 
# This is Distribution is also known as Bell Curve because of its characteristics shape.

# https://www.geeksforgeeks.org/rand-vs-normal-numpy-random-python/

array([1., 1.])

In [30]:
arr = np.random.randint(2,10, size =(3,3) )  # 9 random numbers between 2 and 10 in a 3x3 matrix
arr

array([[4, 9, 4],
       [4, 8, 8],
       [9, 9, 4]])

In [33]:
arr = np.arange(10)
np.random.shuffle(arr)
arr

array([5, 9, 2, 0, 6, 4, 3, 8, 7, 1])

In [35]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.random.shuffle(arr)
arr

array([5, 0, 4, 1, 6, 3, 2, 7, 8, 9])

In [37]:
np.random.rand(2, 4)

array([[1., 0., 1., 1.],
       [0., 0., 1., 0.]])

### 1.1  - Create a 1D array of the first 1000 odd numbers

In [38]:
print(np.linspace(1,1999,1000))

[1.e+00 3.e+00 5.e+00 7.e+00 9.e+00 1.e+01 1.e+01 2.e+01 2.e+01 2.e+01
 2.e+01 2.e+01 2.e+01 3.e+01 3.e+01 3.e+01 3.e+01 4.e+01 4.e+01 4.e+01
 4.e+01 4.e+01 4.e+01 5.e+01 5.e+01 5.e+01 5.e+01 6.e+01 6.e+01 6.e+01
 6.e+01 6.e+01 6.e+01 7.e+01 7.e+01 7.e+01 7.e+01 8.e+01 8.e+01 8.e+01
 8.e+01 8.e+01 8.e+01 9.e+01 9.e+01 9.e+01 9.e+01 1.e+02 1.e+02 1.e+02
 1.e+02 1.e+02 1.e+02 1.e+02 1.e+02 1.e+02 1.e+02 1.e+02 1.e+02 1.e+02
 1.e+02 1.e+02 1.e+02 1.e+02 1.e+02 1.e+02 1.e+02 1.e+02 1.e+02 1.e+02
 1.e+02 1.e+02 1.e+02 1.e+02 1.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02
 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02
 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02
 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02
 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02
 2.e+02 2.e+02 2.e+02 2.e+02 2.e+02 3.e+02 3.e+02 3.e+02 3.e+02 3.e+02
 3.e+02 3.e+02 3.e+02 3.e+02 3.e+02 3.e+02 3.e+02 3.e+02 3.e+02 3.e+02
 3.e+02 3.e+02 3.e+02 3.e+02 3.e+02 3.e+02 3.e+02 3.e+02 3.e+02 3.e+02
 3.e+02 3.e+02 3.e+02 3.e+02 3.e+02 3.e+02 3.e+02 3.e+02 3.e+02 3.e+02
 3.e+02 3.e+02 3.e+02 3.e+02 3.e+02 3.e+02 3.e+02 3.e+02 3.e+02 3.e+02
 3.e+02 3.e+02 3.e+02 3.e+02 3.e+02 4.e+02 4.e+02 4.e+02 4.e+02 4.e+02
 4.e+02 4.e+02 4.e+02 4.e+02 4.e+02 4.e+02 4.e+02 4.e+02 4.e+02 4.e+02
 4.e+02 4.e+02 4.e+02 4.e+02 4.e+02 4.e+02 4.e+02 4.e+02 4.e+02 4.e+02
 4.e+02 4.e+02 4.e+02 4.e+02 4.e+02 4.e+02 4.e+02 4.e+02 4.e+02 4.e+02
 4.e+02 4.e+02 4.e+02 4.e+02 4.e+02 4.e+02 4.e+02 4.e+02 4.e+02 4.e+02
 4.e+02 4.e+02 4.e+02 4.e+02 4.e+02 5.e+02 5.e+02 5.e+02 5.e+02 5.e+02
 5.e+02 5.e+02 5.e+02 5.e+02 5.e+02 5.e+02 5.e+02 5.e+02 5.e+02 5.e+02
 5.e+02 5.e+02 5.e+02 5.e+02 5.e+02 5.e+02 5.e+02 5.e+02 5.e+02 5.e+02
 5.e+02 5.e+02 5.e+02 5.e+02 5.e+02 5.e+02 5.e+02 5.e+02 5.e+02 5.e+02
 5.e+02 5.e+02 5.e+02 5.e+02 5.e+02 5.e+02 5.e+02 5.e+02 5.e+02 5.e+02
 5.e+02 5.e+02 5.e+02 5.e+02 5.e+02 6.e+02 6.e+02 6.e+02 6.e+02 6.e+02
 6.e+02 6.e+02 6.e+02 6.e+02 6.e+02 6.e+02 6.e+02 6.e+02 6.e+02 6.e+02
 6.e+02 6.e+02 6.e+02 6.e+02 6.e+02 6.e+02 6.e+02 6.e+02 6.e+02 6.e+02
 6.e+02 6.e+02 6.e+02 6.e+02 6.e+02 6.e+02 6.e+02 6.e+02 6.e+02 6.e+02
 6.e+02 6.e+02 6.e+02 6.e+02 6.e+02 6.e+02 6.e+02 6.e+02 6.e+02 6.e+02
 6.e+02 6.e+02 6.e+02 6.e+02 6.e+02 7.e+02 7.e+02 7.e+02 7.e+02 7.e+02
 7.e+02 7.e+02 7.e+02 7.e+02 7.e+02 7.e+02 7.e+02 7.e+02 7.e+02 7.e+02
 7.e+02 7.e+02 7.e+02 7.e+02 7.e+02 7.e+02 7.e+02 7.e+02 7.e+02 7.e+02
 7.e+02 7.e+02 7.e+02 7.e+02 7.e+02 7.e+02 7.e+02 7.e+02 7.e+02 7.e+02
 7.e+02 7.e+02 7.e+02 7.e+02 7.e+02 7.e+02 7.e+02 7.e+02 7.e+02 7.e+02
 7.e+02 7.e+02 7.e+02 7.e+02 7.e+02 8.e+02 8.e+02 8.e+02 8.e+02 8.e+02
 8.e+02 8.e+02 8.e+02 8.e+02 8.e+02 8.e+02 8.e+02 8.e+02 8.e+02 8.e+02
 8.e+02 8.e+02 8.e+02 8.e+02 8.e+02 8.e+02 8.e+02 8.e+02 8.e+02 8.e+02
 8.e+02 8.e+02 8.e+02 8.e+02 8.e+02 8.e+02 8.e+02 8.e+02 8.e+02 8.e+02
 8.e+02 8.e+02 8.e+02 8.e+02 8.e+02 8.e+02 8.e+02 8.e+02 8.e+02 8.e+02
 8.e+02 8.e+02 8.e+02 8.e+02 8.e+02 9.e+02 9.e+02 9.e+02 9.e+02 9.e+02
 9.e+02 9.e+02 9.e+02 9.e+02 9.e+02 9.e+02 9.e+02 9.e+02 9.e+02 9.e+02
 9.e+02 9.e+02 9.e+02 9.e+02 9.e+02 9.e+02 9.e+02 9.e+02 9.e+02 9.e+02
 9.e+02 9.e+02 9.e+02 9.e+02 9.e+02 9.e+02 9.e+02 9.e+02 9.e+02 9.e+02
 9.e+02 9.e+02 9.e+02 9.e+02 9.e+02 9.e+02 9.e+02 9.e+02 9.e+02 9.e+02
 9.e+02 9.e+02 9.e+02 9.e+02 9.e+02 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03
 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03
 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03
 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03
 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03
 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03
 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03
 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03
 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03
 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03
 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03
 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03
 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03
 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03
 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03
 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03
 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03
 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03
 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03
 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03
 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03
 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03
 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03
 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03
 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03
 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03
 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03
 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03 1.e+03
 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03
 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03
 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03
 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03
 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03
 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03
 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03
 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03
 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03
 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03
 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03
 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03
 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03
 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03
 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03
 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03
 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03
 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03
 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03
 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03
 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03
 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03
 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03
 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03
 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03 2.e+03]

In [218]:
np.set_printoptions(formatter={'float_kind' : '{:f}'.format})
print(np.linspace(1,1999,1000))

[1.000000 3.000000 5.000000 7.000000 9.000000 11.000000 13.000000
 15.000000 17.000000 19.000000 21.000000 23.000000 25.000000 27.000000
 29.000000 31.000000 33.000000 35.000000 37.000000 39.000000 41.000000
 43.000000 45.000000 47.000000 49.000000 51.000000 53.000000 55.000000
 57.000000 59.000000 61.000000 63.000000 65.000000 67.000000 69.000000
 71.000000 73.000000 75.000000 77.000000 79.000000 81.000000 83.000000
 85.000000 87.000000 89.000000 91.000000 93.000000 95.000000 97.000000
 99.000000 101.000000 103.000000 105.000000 107.000000 109.000000
 111.000000 113.000000 115.000000 117.000000 119.000000 121.000000
 123.000000 125.000000 127.000000 129.000000 131.000000 133.000000
 135.000000 137.000000 139.000000 141.000000 143.000000 145.000000
 147.000000 149.000000 151.000000 153.000000 155.000000 157.000000
 159.000000 161.000000 163.000000 165.000000 167.000000 169.000000
 171.000000 173.000000 175.000000 177.000000 179.000000 181.000000
 183.000000 185.000000 187.000000 189.000000 191.000000 193.000000
 195.000000 197.000000 199.000000 201.000000 203.000000 205.000000
 207.000000 209.000000 211.000000 213.000000 215.000000 217.000000
 219.000000 221.000000 223.000000 225.000000 227.000000 229.000000
 231.000000 233.000000 235.000000 237.000000 239.000000 241.000000
 243.000000 245.000000 247.000000 249.000000 251.000000 253.000000
 255.000000 257.000000 259.000000 261.000000 263.000000 265.000000
 267.000000 269.000000 271.000000 273.000000 275.000000 277.000000
 279.000000 281.000000 283.000000 285.000000 287.000000 289.000000
 291.000000 293.000000 295.000000 297.000000 299.000000 301.000000
 303.000000 305.000000 307.000000 309.000000 311.000000 313.000000
 315.000000 317.000000 319.000000 321.000000 323.000000 325.000000
 327.000000 329.000000 331.000000 333.000000 335.000000 337.000000
 339.000000 341.000000 343.000000 345.000000 347.000000 349.000000
 351.000000 353.000000 355.000000 357.000000 359.000000 361.000000
 363.000000 365.000000 367.000000 369.000000 371.000000 373.000000
 375.000000 377.000000 379.000000 381.000000 383.000000 385.000000
 387.000000 389.000000 391.000000 393.000000 395.000000 397.000000
 399.000000 401.000000 403.000000 405.000000 407.000000 409.000000
 411.000000 413.000000 415.000000 417.000000 419.000000 421.000000
 423.000000 425.000000 427.000000 429.000000 431.000000 433.000000
 435.000000 437.000000 439.000000 441.000000 443.000000 445.000000
 447.000000 449.000000 451.000000 453.000000 455.000000 457.000000
 459.000000 461.000000 463.000000 465.000000 467.000000 469.000000
 471.000000 473.000000 475.000000 477.000000 479.000000 481.000000
 483.000000 485.000000 487.000000 489.000000 491.000000 493.000000
 495.000000 497.000000 499.000000 501.000000 503.000000 505.000000
 507.000000 509.000000 511.000000 513.000000 515.000000 517.000000
 519.000000 521.000000 523.000000 525.000000 527.000000 529.000000
 531.000000 533.000000 535.000000 537.000000 539.000000 541.000000
 543.000000 545.000000 547.000000 549.000000 551.000000 553.000000
 555.000000 557.000000 559.000000 561.000000 563.000000 565.000000
 567.000000 569.000000 571.000000 573.000000 575.000000 577.000000
 579.000000 581.000000 583.000000 585.000000 587.000000 589.000000
 591.000000 593.000000 595.000000 597.000000 599.000000 601.000000
 603.000000 605.000000 607.000000 609.000000 611.000000 613.000000
 615.000000 617.000000 619.000000 621.000000 623.000000 625.000000
 627.000000 629.000000 631.000000 633.000000 635.000000 637.000000
 639.000000 641.000000 643.000000 645.000000 647.000000 649.000000
 651.000000 653.000000 655.000000 657.000000 659.000000 661.000000
 663.000000 665.000000 667.000000 669.000000 671.000000 673.000000
 675.000000 677.000000 679.000000 681.000000 683.000000 685.000000
 687.000000 689.000000 691.000000 693.000000 695.000000 697.000000
 699.000000 701.000000 703.000000 705.000000 707.000000 709.000000
 711.000000 713.000000 715.000000 717.000000 719.000000 721.000000
 723.000000 725.000000 727.000000 729.000000 731.000000 733.000000
 735.000000 737.000000 739.000000 741.000000 743.000000 745.000000
 747.000000 749.000000 751.000000 753.000000 755.000000 757.000000
 759.000000 761.000000 763.000000 765.000000 767.000000 769.000000
 771.000000 773.000000 775.000000 777.000000 779.000000 781.000000
 783.000000 785.000000 787.000000 789.000000 791.000000 793.000000
 795.000000 797.000000 799.000000 801.000000 803.000000 805.000000
 807.000000 809.000000 811.000000 813.000000 815.000000 817.000000
 819.000000 821.000000 823.000000 825.000000 827.000000 829.000000
 831.000000 833.000000 835.000000 837.000000 839.000000 841.000000
 843.000000 845.000000 847.000000 849.000000 851.000000 853.000000
 855.000000 857.000000 859.000000 861.000000 863.000000 865.000000
 867.000000 869.000000 871.000000 873.000000 875.000000 877.000000
 879.000000 881.000000 883.000000 885.000000 887.000000 889.000000
 891.000000 893.000000 895.000000 897.000000 899.000000 901.000000
 903.000000 905.000000 907.000000 909.000000 911.000000 913.000000
 915.000000 917.000000 919.000000 921.000000 923.000000 925.000000
 927.000000 929.000000 931.000000 933.000000 935.000000 937.000000
 939.000000 941.000000 943.000000 945.000000 947.000000 949.000000
 951.000000 953.000000 955.000000 957.000000 959.000000 961.000000
 963.000000 965.000000 967.000000 969.000000 971.000000 973.000000
 975.000000 977.000000 979.000000 981.000000 983.000000 985.000000
 987.000000 989.000000 991.000000 993.000000 995.000000 997.000000
 999.000000 1001.000000 1003.000000 1005.000000 1007.000000 1009.000000
 1011.000000 1013.000000 1015.000000 1017.000000 1019.000000 1021.000000
 1023.000000 1025.000000 1027.000000 1029.000000 1031.000000 1033.000000
 1035.000000 1037.000000 1039.000000 1041.000000 1043.000000 1045.000000
 1047.000000 1049.000000 1051.000000 1053.000000 1055.000000 1057.000000
 1059.000000 1061.000000 1063.000000 1065.000000 1067.000000 1069.000000
 1071.000000 1073.000000 1075.000000 1077.000000 1079.000000 1081.000000
 1083.000000 1085.000000 1087.000000 1089.000000 1091.000000 1093.000000
 1095.000000 1097.000000 1099.000000 1101.000000 1103.000000 1105.000000
 1107.000000 1109.000000 1111.000000 1113.000000 1115.000000 1117.000000
 1119.000000 1121.000000 1123.000000 1125.000000 1127.000000 1129.000000
 1131.000000 1133.000000 1135.000000 1137.000000 1139.000000 1141.000000
 1143.000000 1145.000000 1147.000000 1149.000000 1151.000000 1153.000000
 1155.000000 1157.000000 1159.000000 1161.000000 1163.000000 1165.000000
 1167.000000 1169.000000 1171.000000 1173.000000 1175.000000 1177.000000
 1179.000000 1181.000000 1183.000000 1185.000000 1187.000000 1189.000000
 1191.000000 1193.000000 1195.000000 1197.000000 1199.000000 1201.000000
 1203.000000 1205.000000 1207.000000 1209.000000 1211.000000 1213.000000
 1215.000000 1217.000000 1219.000000 1221.000000 1223.000000 1225.000000
 1227.000000 1229.000000 1231.000000 1233.000000 1235.000000 1237.000000
 1239.000000 1241.000000 1243.000000 1245.000000 1247.000000 1249.000000
 1251.000000 1253.000000 1255.000000 1257.000000 1259.000000 1261.000000
 1263.000000 1265.000000 1267.000000 1269.000000 1271.000000 1273.000000
 1275.000000 1277.000000 1279.000000 1281.000000 1283.000000 1285.000000
 1287.000000 1289.000000 1291.000000 1293.000000 1295.000000 1297.000000
 1299.000000 1301.000000 1303.000000 1305.000000 1307.000000 1309.000000
 1311.000000 1313.000000 1315.000000 1317.000000 1319.000000 1321.000000
 1323.000000 1325.000000 1327.000000 1329.000000 1331.000000 1333.000000
 1335.000000 1337.000000 1339.000000 1341.000000 1343.000000 1345.000000
 1347.000000 1349.000000 1351.000000 1353.000000 1355.000000 1357.000000
 1359.000000 1361.000000 1363.000000 1365.000000 1367.000000 1369.000000
 1371.000000 1373.000000 1375.000000 1377.000000 1379.000000 1381.000000
 1383.000000 1385.000000 1387.000000 1389.000000 1391.000000 1393.000000
 1395.000000 1397.000000 1399.000000 1401.000000 1403.000000 1405.000000
 1407.000000 1409.000000 1411.000000 1413.000000 1415.000000 1417.000000
 1419.000000 1421.000000 1423.000000 1425.000000 1427.000000 1429.000000
 1431.000000 1433.000000 1435.000000 1437.000000 1439.000000 1441.000000
 1443.000000 1445.000000 1447.000000 1449.000000 1451.000000 1453.000000
 1455.000000 1457.000000 1459.000000 1461.000000 1463.000000 1465.000000
 1467.000000 1469.000000 1471.000000 1473.000000 1475.000000 1477.000000
 1479.000000 1481.000000 1483.000000 1485.000000 1487.000000 1489.000000
 1491.000000 1493.000000 1495.000000 1497.000000 1499.000000 1501.000000
 1503.000000 1505.000000 1507.000000 1509.000000 1511.000000 1513.000000
 1515.000000 1517.000000 1519.000000 1521.000000 1523.000000 1525.000000
 1527.000000 1529.000000 1531.000000 1533.000000 1535.000000 1537.000000
 1539.000000 1541.000000 1543.000000 1545.000000 1547.000000 1549.000000
 1551.000000 1553.000000 1555.000000 1557.000000 1559.000000 1561.000000
 1563.000000 1565.000000 1567.000000 1569.000000 1571.000000 1573.000000
 1575.000000 1577.000000 1579.000000 1581.000000 1583.000000 1585.000000
 1587.000000 1589.000000 1591.000000 1593.000000 1595.000000 1597.000000
 1599.000000 1601.000000 1603.000000 1605.000000 1607.000000 1609.000000
 1611.000000 1613.000000 1615.000000 1617.000000 1619.000000 1621.000000
 1623.000000 1625.000000 1627.000000 1629.000000 1631.000000 1633.000000
 1635.000000 1637.000000 1639.000000 1641.000000 1643.000000 1645.000000
 1647.000000 1649.000000 1651.000000 1653.000000 1655.000000 1657.000000
 1659.000000 1661.000000 1663.000000 1665.000000 1667.000000 1669.000000
 1671.000000 1673.000000 1675.000000 1677.000000 1679.000000 1681.000000
 1683.000000 1685.000000 1687.000000 1689.000000 1691.000000 1693.000000
 1695.000000 1697.000000 1699.000000 1701.000000 1703.000000 1705.000000
 1707.000000 1709.000000 1711.000000 1713.000000 1715.000000 1717.000000
 1719.000000 1721.000000 1723.000000 1725.000000 1727.000000 1729.000000
 1731.000000 1733.000000 1735.000000 1737.000000 1739.000000 1741.000000
 1743.000000 1745.000000 1747.000000 1749.000000 1751.000000 1753.000000
 1755.000000 1757.000000 1759.000000 1761.000000 1763.000000 1765.000000
 1767.000000 1769.000000 1771.000000 1773.000000 1775.000000 1777.000000
 1779.000000 1781.000000 1783.000000 1785.000000 1787.000000 1789.000000
 1791.000000 1793.000000 1795.000000 1797.000000 1799.000000 1801.000000
 1803.000000 1805.000000 1807.000000 1809.000000 1811.000000 1813.000000
 1815.000000 1817.000000 1819.000000 1821.000000 1823.000000 1825.000000
 1827.000000 1829.000000 1831.000000 1833.000000 1835.000000 1837.000000
 1839.000000 1841.000000 1843.000000 1845.000000 1847.000000 1849.000000
 1851.000000 1853.000000 1855.000000 1857.000000 1859.000000 1861.000000
 1863.000000 1865.000000 1867.000000 1869.000000 1871.000000 1873.000000
 1875.000000 1877.000000 1879.000000 1881.000000 1883.000000 1885.000000
 1887.000000 1889.000000 1891.000000 1893.000000 1895.000000 1897.000000
 1899.000000 1901.000000 1903.000000 1905.000000 1907.000000 1909.000000
 1911.000000 1913.000000 1915.000000 1917.000000 1919.000000 1921.000000
 1923.000000 1925.000000 1927.000000 1929.000000 1931.000000 1933.000000
 1935.000000 1937.000000 1939.000000 1941.000000 1943.000000 1945.000000
 1947.000000 1949.000000 1951.000000 1953.000000 1955.000000 1957.000000
 1959.000000 1961.000000 1963.000000 1965.000000 1967.000000 1969.000000
 1971.000000 1973.000000 1975.000000 1977.000000 1979.000000 1981.000000
 1983.000000 1985.000000 1987.000000 1989.000000 1991.000000 1993.000000
 1995.000000 1997.000000 1999.000000]

### 1.2  - Create a 2D array of size (5,10) containing random numbers between 1 and 2

In [39]:
np.random.rand(5,10)+1

array([[1., 1., 1., 2., 2., 2., 2., 2., 1., 1.],
       [2., 2., 2., 2., 1., 1., 1., 2., 2., 1.],
       [1., 1., 1., 2., 1., 1., 1., 1., 2., 2.],
       [1., 1., 1., 2., 1., 1., 1., 2., 2., 1.],
       [2., 1., 2., 2., 2., 1., 1., 2., 2., 2.]])

### 1.3 - Create a 10x10 Identity matrix where all the numbers are in integer format

In [40]:
np.identity(10, dtype='int')

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

There are multiple ways in which numpy arrays can be created:

- np.array()
- np.ones() / np.zeros()
- np.full()
- np.arange()
- np.linspace()
- np.identity()
- np.random()

---
## <font color = blue> Reshape the array</font>
---

### 2.1 `np_array.reshape()`

In [41]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [43]:
np.arange(12).reshape(12,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

### 2.2 `arr.flatten()`

In [48]:
arr = np.array([[10,20,30],[40,50,60],[18,18,18]])
print(arr.flatten().shape)
print(arr.flatten())

(9,)
[10 20 30 40 50 60 18 18 18]

In [49]:
type(arr.flatten())

numpy.ndarray

In [ ]:
np.flatten()

### 2.3 `np.ravel()`

In [50]:
arr

array([[10, 20, 30],
       [40, 50, 60],
       [18, 18, 18]])

In [52]:
# Return a contiguous flattened array.

arr_ravel = np.ravel(arr)  
print(arr_ravel)

[10 20 30 40 50 60 18 18 18]

In [56]:
# Row-wise
np.ravel(arr, order='C')

array([10, 20, 30, 40, 50, 60, 18, 18, 18])

In [57]:
# Column-wise
np.ravel(arr, order='F')

array([10, 40, 18, 20, 50, 18, 30, 60, 18])

### 2.1 - Find the transpose of the given array without using `np.transpose`

In [64]:
arr = np.arange(50)
print(arr.shape)

(50,)

In [66]:
arr = arr.reshape(50,1)
print(arr.shape)

(50, 1)

### 2.2 Convert the following 2-D array into a 1-D array in columnar fashion (the first few elements should belong to the first column)

In [68]:
arr = np.arange(50).reshape(5,10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [69]:
np.ravel(arr, order='F')

array([ 0, 10, 20, 30, 40,  1, 11, 21, 31, 41,  2, 12, 22, 32, 42,  3, 13,
       23, 33, 43,  4, 14, 24, 34, 44,  5, 15, 25, 35, 45,  6, 16, 26, 36,
       46,  7, 17, 27, 37, 47,  8, 18, 28, 38, 48,  9, 19, 29, 39, 49])

The following commands can be used to reshape the array

- np.reshape()
- np.ravel()
- np.flatten()

The one command np.reshape() is enough to perform all reshaping operations. The other two are just good to know if you want to flatten a dataset in a single command, without inspecting it first.

---
## <font color=blue>  Join and stack two arrays</font>
---

- Vertical stacking (row wise) using `vstack()`
- Horizontal stacking (column wise) using `hstack()`
- Depth wise stacking (along third axis) using `dstack()`
- `concatenate()` function creates a new array by appending arrays after each other, along a given axis
- `append()` function appends an element to an array and creates a new copy of the array

In [70]:
import numpy as np


array_1 = np.arange(10).reshape(2,5)
print(array_1)

print("-"*30)

array_2 = np.arange(13,23,1).reshape(2,5)
print(array_2)

[[0 1 2 3 4]
 [5 6 7 8 9]]
------------------------------
[[13 14 15 16 17]
 [18 19 20 21 22]]

### 3.1 `np.vstack()`

In [71]:
array_vstack = np.vstack([array_1,array_2])
print(array_vstack)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [13 14 15 16 17]
 [18 19 20 21 22]]

In [72]:
print(array_vstack.shape)

(4, 5)

### 3.2 `np.hstack()`

In [73]:
array_hstack = np.hstack([array_1,array_2])
print(array_hstack)

[[ 0  1  2  3  4 13 14 15 16 17]
 [ 5  6  7  8  9 18 19 20 21 22]]

In [74]:
print(array_hstack.shape)

(2, 10)

In [128]:
print(array_1)
print("-"*30)
print(array_2)

[[0 1 2 3 4]
 [5 6 7 8 9]]
------------------------------
[[13 14 15 16 17]
 [18 19 20 21 22]]

### 3.3 `np.dstack()`

In [75]:
array_dstack = np.dstack([array_1,array_2])
print(array_dstack)

[[[ 0 13]
  [ 1 14]
  [ 2 15]
  [ 3 16]
  [ 4 17]]

 [[ 5 18]
  [ 6 19]
  [ 7 20]
  [ 8 21]
  [ 9 22]]]

In [76]:
print(array_dstack.shape) # two sets of 5x2 matrices

(2, 5, 2)

### 3.4 `np.concatenate()`

In [77]:
array_concatenate = np.concatenate([array_1,array_2])
print(array_concatenate)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [13 14 15 16 17]
 [18 19 20 21 22]]

In [78]:
print(array_concatenate.shape) # same as vstack

(4, 5)

### 3.5 `np.append()`

In [79]:
array_append = np.append(array_1,array_2)
print(array_append)

[ 0  1  2  3  4  5  6  7  8  9 13 14 15 16 17 18 19 20 21 22]

In [80]:
print(array_append.shape)

(20,)

In [81]:
array_append = np.append(array_1,array_2,axis =1)
print(array_append)

[[ 0  1  2  3  4 13 14 15 16 17]
 [ 5  6  7  8  9 18 19 20 21 22]]

In [82]:
print(array_append.shape)

(2, 10)

In [83]:
array_append = np.append(array_1,array_2,axis = 0)
print(array_append)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [13 14 15 16 17]
 [18 19 20 21 22]]

In [84]:
print(array_append.shape)

(4, 5)

### 3.1 Represent the chess board as a numpy array
The following are the numerical mapping to chess pieces:
- Pawns: 1
- Rook: 2
- Knight: 3
- Bishop: 4
- King: 5
- Queen: 6
- Empty spaces: 0

In [86]:
row_1 = [2,3,4,5,6,4,3,2]
row_2 = np.ones(8,dtype=int)
row_3_4 = np.zeros(16,dtype=int).reshape(2,8)
top_half = np.vstack([row_1,row_2,row_3_4])
print(top_half)

[[2 3 4 5 6 4 3 2]
 [1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]

In [89]:
bottom_half = np.flip(top_half,axis = 0)
print(bottom_half)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1]
 [2 3 4 5 6 4 3 2]]

In [85]:
row_1 = [2,3,4,5,6,4,3,2]
row_2 = np.ones(8,dtype=int)
row_3_4 = np.zeros(16,dtype=int).reshape(2,8)
top_half = np.vstack([row_1,row_2,row_3_4])
bottom_half = np.flip(top_half,axis = 0)

chess_board = np.vstack([top_half,bottom_half])
chess_board

array([[2, 3, 4, 5, 6, 4, 3, 2],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [2, 3, 4, 5, 6, 4, 3, 2]])

### 3.2 Create an array of size 10x10 ,where the borders are all ones and the inside elements are zeros

In [105]:
arr = np.zeros(100, dtype=int).reshape(10,10)
print(arr)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]

In [106]:
arr[0 , :] = arr[-1 , : ] = arr[ : , 0] = arr[ : , -1] = 1
arr

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [114]:
arr = np.ones(100, dtype=int).reshape(10,10)
print(arr)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]

In [115]:
arr[1:-1 , 1:-1] = 0
arr

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

Any two arrays can be joined in the following formats:
- vstack() - Vertical stacking (row wise)
- hstack() - Horizontal stacking (column wise)
- dstack() - Depth wise stacking (along third axis)
- concatenate() - Creates a new array by appending arrays after each other, along a given axis
- append() - Appends an element to an array and creates a new copy of the array

In [123]:
np.identity(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [122]:
arr = np.array([[10,20,30],[40,50,60]])
print(arr.flatten().shape)

(6,)

In [124]:
arr1 = np.array([[0,0],[0,0]])
arr2 = np.array([[1],[1]])
arr3 = np.array([1,1,1])

In [126]:
arr4 = np.hstack([arr1,arr2])
print(np.vstack([arr4,arr3]))

[[0 0 1]
 [0 0 1]
 [1 1 1]]

---
## <font color = blue> Perform basic Slicing and Indexing</font>
---

### 4.1 `Location based indexing`

In [136]:
arr = np.array([[10,20,30],[40,50,60],[70,80,90]])
arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [137]:
print(arr[0])

[10 20 30]

In [138]:
print(arr[0][0])

10

In [139]:
print(arr[0,0])

10

In [140]:
print(arr[-1])

[70 80 90]

In [141]:
print(arr[:,1:3])

[[20 30]
 [50 60]
 [80 90]]

In [142]:
print(arr[[0,1,2],[1,0,0]])

[20 40 70]

### 4.2 `Boolean Indexing`

### `np.where(  )`

- Returns the index based on the boolean

### `np.isnan()` 
- Returns the boolean of data == np.nan

In [143]:
location = np.array(["Mumbai","Mumbai","Delhi","Chennai","Bangalore"]) #2 branches in Mumbai
sales_data = np.random.randint(1,10,size=(5,5))
sales_data = sales_data.astype(float)
sales_data[[[1,4],[2,3]]] = np.nan
print(sales_data)

[[ 7.  3.  5.  9.  9.]
 [ 9.  1. nan  1.  2.]
 [ 8.  3.  2.  2.  8.]
 [ 6.  2.  6.  5.  2.]
 [ 3.  7.  5. nan  5.]]

In [144]:
sales_data[location =="Mumbai"]
# depending on which index is True, it prints that row
# In this case, mumbai is at index 2, therefore row no. 2 will be printed

array([[ 7.,  3.,  5.,  9.,  9.],
       [ 9.,  1., nan,  1.,  2.]])

In [145]:
(location =="Mumbai")

array([ True,  True, False, False, False])

In [146]:
np.where(location == "Mumbai")

(array([0, 1], dtype=int64),)

In [147]:
# if the match does not happen , then all values are false.
sales_data[location =="Kolkata"]
# the o/p in such a case is indicating shape as(0 rows, 3 features)

array([], shape=(0, 5), dtype=float64)

We can also use Boolean indexing for selecting some elements of an array that satisfy a
particular condition. For example, in the previous array suppose we want to only select
non-zero elements.
We can do that easily using the following code.

In [148]:
sales_data >4

array([[ True, False,  True,  True,  True],
       [ True, False, False, False, False],
       [ True, False, False, False,  True],
       [ True, False,  True,  True, False],
       [False,  True,  True, False,  True]])

In [149]:
sales_data == np.nan

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

`np.nan==np.nan` is always `False`

We use np.isnan() to find out the nan values in the data

In [150]:
np.isnan(sales_data)

array([[False, False, False, False, False],
       [False, False,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True, False]])

In [151]:
np.where(np.isnan(sales_data))

(array([1, 4], dtype=int64), array([2, 3], dtype=int64))

In [152]:
sales_data[np.isnan(sales_data)] = 0.0 # all nan values will be reset to 0
sales_data

array([[7., 3., 5., 9., 9.],
       [9., 1., 0., 1., 2.],
       [8., 3., 2., 2., 8.],
       [6., 2., 6., 5., 2.],
       [3., 7., 5., 0., 5.]])

### 4.3 `np.ndenumerate()`

ndenumerate return the co-ordinates and corresponding values in the co-ordinates

In [153]:
A = np.array([[11, 22, 23], [33, 43, 55]])

In [154]:
np.ndenumerate(A)

In [155]:
for index, x in np.ndenumerate(A):
    print(index, x)

(0, 0) 11
(0, 1) 22
(0, 2) 23
(1, 0) 33
(1, 1) 43
(1, 2) 55

### 4.1 - Create a 1D array of alternating 0's and 1's of size 500

In [156]:
arr = np.zeros(500,dtype=int)
arr[1::2]=1
arr

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

### 4.2 - Remove all the prime numbers from the following array and replace it with 0

np.vectorize() - 
Define a vectorized function which takes a nested sequence of objects or numpy arrays as inputs and returns a single numpy array or a tuple of numpy arrays. The vectorized function evaluates `pyfunc` over successive tuples of the input arrays like the python map function, except it uses the broadcasting rules of numpy.

In [157]:
def isprime(number):
    for i in range(2,number):
        if(number%i == 0 and number!=2 ):
            return False
    return True



primecheck = np.vectorize(isprime) ##vectorizes isprime() to be applied on np array
arr = np.arange(2,102).reshape(20,5)

arr[primecheck(arr)]=0
arr

array([[  0,   0,   4,   0,   6],
       [  0,   8,   9,  10,   0],
       [ 12,   0,  14,  15,  16],
       [  0,  18,   0,  20,  21],
       [ 22,   0,  24,  25,  26],
       [ 27,  28,   0,  30,   0],
       [ 32,  33,  34,  35,  36],
       [  0,  38,  39,  40,   0],
       [ 42,   0,  44,  45,  46],
       [  0,  48,  49,  50,  51],
       [ 52,   0,  54,  55,  56],
       [ 57,  58,   0,  60,   0],
       [ 62,  63,  64,  65,  66],
       [  0,  68,  69,  70,   0],
       [ 72,   0,  74,  75,  76],
       [ 77,  78,   0,  80,  81],
       [ 82,   0,  84,  85,  86],
       [ 87,  88,   0,  90,  91],
       [ 92,  93,  94,  95,  96],
       [  0,  98,  99, 100,   0]])

### 4.3 - In the previous array, find the position of all the squares, $1^2, 2^2, 3^2$...

In [195]:
arr = np.arange(2,102).reshape(20,5)

In [196]:
square = np.square(np.arange(1,11))    
print(square)

[  1   4   9  16  25  36  49  64  81 100]

In [197]:
def squarenum(num):
    if num  in square:
        return True
    return False

squarecheck = np.vectorize(squarenum)

In [198]:
arr[squarecheck(arr)]

array([  4,   9,  16,  25,  36,  49,  64,  81, 100])

In [200]:
arr[squarecheck(arr)]= 0
arr

array([[  2,   3,   0,   5,   6],
       [  7,   8,   0,  10,  11],
       [ 12,  13,  14,  15,   0],
       [ 17,  18,  19,  20,  21],
       [ 22,  23,  24,   0,  26],
       [ 27,  28,  29,  30,  31],
       [ 32,  33,  34,  35,   0],
       [ 37,  38,  39,  40,  41],
       [ 42,  43,  44,  45,  46],
       [ 47,  48,   0,  50,  51],
       [ 52,  53,  54,  55,  56],
       [ 57,  58,  59,  60,  61],
       [ 62,  63,   0,  65,  66],
       [ 67,  68,  69,  70,  71],
       [ 72,  73,  74,  75,  76],
       [ 77,  78,  79,  80,   0],
       [ 82,  83,  84,  85,  86],
       [ 87,  88,  89,  90,  91],
       [ 92,  93,  94,  95,  96],
       [ 97,  98,  99,   0, 101]])

In [201]:
np.where(arr == 0)

(array([ 0,  1,  2,  4,  6,  9, 12, 15, 19], dtype=int64),
 array([2, 2, 4, 3, 4, 2, 2, 4, 3], dtype=int64))

In [203]:
for index,val in np.ndenumerate(arr):
    if val== 0:
        print(index)

(0, 2)
(1, 2)
(2, 4)
(4, 3)
(6, 4)
(9, 2)
(12, 2)
(15, 4)
(19, 3)

Some basic indexing and slicing can be done with the following set of commands:

- arr[:,:] - Returns the sliced portion of the 2D array
- np.where() - Return the indices based on the boolean condition
- np.ndeunmerate() - Returns the values along with it corresponding indices

---
## <font color=blue> Perform operations on Arrays (addition, multiplication etc.)</font>
---

In [204]:
arr1 = np.arange(15).reshape(5,3)
arr1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [205]:
#adding a constant
arr1 + 5

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [206]:
#product using constant
arr1 * 2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [207]:
arr2 = np.arange(5).reshape(5,1) 
print(arr2)

[[0]
 [1]
 [2]
 [3]
 [4]]

In [208]:
#Matrix sum
print(arr2 + arr1) # arr2[i] + arr1's entire row

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]
 [16 17 18]]

In [209]:
#Transpose
arr1.T

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [210]:
#matrix multiplication
arr1.T @ arr2

array([[ 90],
       [100],
       [110]])

In [211]:
arr3 = np.random.randn(3,5)

In [212]:
# dot product
arr1.dot(arr3)

array([[ -0.,  -2.,   2.,  -5.,  -3.],
       [ -0.,  -1.,   7., -12.,  -6.],
       [ -1.,   1.,  12., -19.,  -9.],
       [ -1.,   3.,  17., -26., -12.],
       [ -1.,   4.,  22., -33., -15.]])

In [213]:
arr = np.random.rand(16).reshape(4,4)

In [214]:
np.linalg.inv(arr)

array([[-1.,  1.,  2., -2.],
       [ 1.,  2.,  0., -2.],
       [-1.,  2.,  0., -0.],
       [ 1., -2., -1.,  2.]])

In [215]:
arr = np.identity(4)
np.linalg.inv(arr)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [216]:
np.ones(5).T @ np.ones(5)

5.0

 ### 5.1 - Verify that `np.linalg.inv()` computes the inverse of a matrix

In [217]:
arr = np.random.rand(3,3)
arr_inv = np.linalg.inv(arr)
arr @ arr_inv

array([[ 1.e+00,  5.e-17,  1.e-16],
       [-3.e-16,  1.e+00,  3.e-16],
       [-6.e-17,  6.e-17,  1.e+00]])

Matrix A= IA , then A * inv A = I

In [219]:
np.set_printoptions(formatter= {"float_kind" : '{:f}'.format})
arr @ arr_inv

array([[1.000000, 0.000000, 0.000000],
       [-0.000000, 1.000000, 0.000000],
       [-0.000000, 0.000000, 1.000000]])

### 5.2 - Extract the row-wise and column-wise sum of the following array

In [221]:
arr = np.arange(100).reshape(10,10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [222]:
# row wise sum

np.sum(arr, axis=1)

array([ 45, 145, 245, 345, 445, 545, 645, 745, 845, 945])

In [223]:
# column wise sum

np.sum(arr, axis=0)

array([450, 460, 470, 480, 490, 500, 510, 520, 530, 540])

In [227]:
# grand total

np.sum(arr)

4950

Numpy is very efficient in performing Matrix operations 

- M1 @ M2 - Multiplies the matrices M1 and M2 - Vector product
- M1.dot(M2) - Performs dot product operation over M1 and M2
- np.linalg.inv() - Calculates the inverse of the matrix

In [224]:
arr = np.arange(100).reshape(10,10)
for index,x in np.ndenumerate(arr):
    if x==50:
        print(index)

(5, 0)

In [225]:
print(np.ones(5) @ np.ones(5).T)

5.0

---
## <font color = blue>Sorting the array</font>
---
### 6.1 `np.sort()`

In [228]:
arr = np.random.randint(1,7, size=[8, 4])
arr

array([[6, 6, 3, 1],
       [2, 5, 1, 3],
       [5, 3, 3, 1],
       [3, 5, 3, 5],
       [2, 5, 1, 3],
       [3, 4, 6, 3],
       [1, 2, 4, 2],
       [2, 2, 3, 1]])

We have a random array of 8 rows and 4 columns.

If you use the np.sort function with axis=0, all the columns will be sorted in ascending order independent of eachother, effectively compromising the integrity of the row items. In simple terms, the values in each row gets corrupted with values from other rows.

In [229]:
# Sort each columns of arr
np.sort(arr, axis=0)

array([[1, 2, 1, 1],
       [2, 2, 1, 1],
       [2, 3, 3, 1],
       [2, 4, 3, 2],
       [3, 5, 3, 3],
       [3, 5, 3, 3],
       [5, 5, 4, 3],
       [6, 6, 6, 5]])

Since I don’t want the content of rows to be disturbed, I resort to an indirect method using np.argsort.

### 6.2 `np.argsort()`

Let’s first understand what np.argsort does.

np.argsort returns the index positions of that would make a given 1d array sorted.

In [230]:
# Get the index positions that would sort the array
x = np.array([1, 10, 5, 2, 8, 9])
sort_index = np.argsort(x)
print(sort_index)

[0 3 2 4 5 1]

How to interpret this?

In array ‘x’, the 0th item is the smallest, 3rd item is the second smallest and so on.

In [231]:
x[sort_index]

array([ 1,  2,  5,  8,  9, 10])

Now, in order to sort the original arr, I am going to do an argsort on the 1st column and use the resulting index positions to sort arr. See the code.

In [232]:
# Argsort the first column
sorted_index_1stcol = arr[:, 0].argsort()

# Sort 'arr' by first column without disturbing the integrity of rows
arr[sorted_index_1stcol]

array([[1, 2, 4, 2],
       [2, 5, 1, 3],
       [2, 5, 1, 3],
       [2, 2, 3, 1],
       [3, 5, 3, 5],
       [3, 4, 6, 3],
       [5, 3, 3, 1],
       [6, 6, 3, 1]])

To sort it in decreasing order, simply reverse the argsorted index.

In [233]:
# Descending sort
arr[sorted_index_1stcol[::-1]]

array([[6, 6, 3, 1],
       [5, 3, 3, 1],
       [3, 4, 6, 3],
       [3, 5, 3, 5],
       [2, 2, 3, 1],
       [2, 5, 1, 3],
       [2, 5, 1, 3],
       [1, 2, 4, 2]])

### 6.3 `np.lexsort()`

In [234]:
# Sort by column 0, then by column 1
lexsorted_index = np.lexsort((arr[:, 1], arr[:, 0])) 
arr[lexsorted_index]

array([[1, 2, 4, 2],
       [2, 2, 3, 1],
       [2, 5, 1, 3],
       [2, 5, 1, 3],
       [3, 4, 6, 3],
       [3, 5, 3, 5],
       [5, 3, 3, 1],
       [6, 6, 3, 1]])

### 6.1 Sort the following array based on the first column, in the descending order

In [235]:
arr = np.random.randint(1,7, size=[8, 4])

sorted_index_1stcol = arr[:, 0].argsort()
arr[sorted_index_1stcol[::-1]]

array([[6, 1, 4, 4],
       [5, 1, 4, 5],
       [4, 6, 6, 3],
       [4, 6, 3, 3],
       [3, 6, 1, 2],
       [3, 4, 3, 2],
       [2, 1, 2, 1],
       [1, 4, 6, 4]])

In [226]:
x = np.array([1,2,3,4,5,6])
sort_index = np.argsort(x)
print(sort_index)

[0 1 2 3 4 5]

Numpy is very efficient in performing sorting
- np.sort() - Sorts all the columns of the matrix - Row information is lost
- np.argsort() - Returns the order of indices on which the rows have to be arranged, based on a singular column
- np.lexsort() - Same as np.argsort() but can be done over multiple columns

---
## <font color=blue> Size of objects in Memory</font>
---

In [236]:
import sys

In [237]:
# An integer in Python is > 24bytes
sys.getsizeof(1)

28

In [238]:
sys.getsizeof(10)

28

In [239]:
# Longs are even larger
sys.getsizeof(10**100)

72

In [240]:
# Numpy size is much smaller
np.dtype(int).itemsize

4

In [241]:
# Numpy size is much smaller
np.dtype(np.int8).itemsize

1

In [242]:
np.dtype(float).itemsize

8

#### Lists are even larger

In [243]:
# A one-element list
sys.getsizeof([1])

64

In [244]:
# An array of one element in numpy
np.array([1]).nbytes

4

#### And performance is also important

In [2]:
l = list(range(100000))
l

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 465,
 466,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 475,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 486,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 505,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 532,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 547,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 556,
 557,
 558,
 559,
 560,
 561,
 562,
 563,
 564,
 565,
 566,
 567,
 568,
 569,
 570,
 571,
 572,
 573,
 574,
 575,
 576,
 577,
 578,
 579,
 580,
 581,
 582,
 583,
 584,
 585,
 586,
 587,
 588,
 589,
 590,
 591,
 592,
 593,
 594,
 595,
 596,
 597,
 598,
 599,
 600,
 601,
 602,
 603,
 604,
 605,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 615,
 616,
 617,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 643,
 644,
 645,
 646,
 647,
 648,
 649,
 650,
 651,
 652,
 653,
 654,
 655,
 656,
 657,
 658,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 667,
 668,
 669,
 670,
 671,
 672,
 673,
 674,
 675,
 676,
 677,
 678,
 679,
 680,
 681,
 682,
 683,
 684,
 685,
 686,
 687,
 688,
 689,
 690,
 691,
 692,
 693,
 694,
 695,
 696,
 697,
 698,
 699,
 700,
 701,
 702,
 703,
 704,
 705,
 706,
 707,
 708,
 709,
 710,
 711,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 719,
 720,
 721,
 722,
 723,
 724,
 725,
 726,
 727,
 728,
 729,
 730,
 731,
 732,
 733,
 734,
 735,
 736,
 737,
 738,
 739,
 740,
 741,
 742,
 743,
 744,
 745,
 746,
 747,
 748,
 749,
 750,
 751,
 752,
 753,
 754,
 755,
 756,
 757,
 758,
 759,
 760,
 761,
 762,
 763,
 764,
 765,
 766,
 767,
 768,
 769,
 770,
 771,
 772,
 773,
 774,
 775,
 776,
 777,
 778,
 779,
 780,
 781,
 782,
 783,
 784,
 785,
 786,
 787,
 788,
 789,
 790,
 791,
 792,
 793,
 794,
 795,
 796,
 797,
 798,
 799,
 800,
 801,
 802,
 803,
 804,
 805,
 806,
 807,
 808,
 809,
 810,
 811,
 812,
 813,
 814,
 815,
 816,
 817,
 818,
 819,
 820,
 821,
 822,
 823,
 824,
 825,
 826,
 827,
 828,
 829,
 830,
 831,
 832,
 833,
 834,
 835,
 836,
 837,
 838,
 839,
 840,
 841,
 842,
 843,
 844,
 845,
 846,
 847,
 848,
 849,
 850,
 851,
 852,
 853,
 854,
 855,
 856,
 857,
 858,
 859,
 860,
 861,
 862,
 863,
 864,
 865,
 866,
 867,
 868,
 869,
 870,
 871,
 872,
 873,
 874,
 875,
 876,
 877,
 878,
 879,
 880,
 881,
 882,
 883,
 884,
 885,
 886,
 887,
 888,
 889,
 890,
 891,
 892,
 893,
 894,
 895,
 896,
 897,
 898,
 899,
 900,
 901,
 902,
 903,
 904,
 905,
 906,
 907,
 908,
 909,
 910,
 911,
 912,
 913,
 914,
 915,
 916,
 917,
 918,
 919,
 920,
 921,
 922,
 923,
 924,
 925,
 926,
 927,
 928,
 929,
 930,
 931,
 932,
 933,
 934,
 935,
 936,
 937,
 938,
 939,
 940,
 941,
 942,
 943,
 944,
 945,
 946,
 947,
 948,
 949,
 950,
 951,
 952,
 953,
 954,
 955,
 956,
 957,
 958,
 959,
 960,
 961,
 962,
 963,
 964,
 965,
 966,
 967,
 968,
 969,
 970,
 971,
 972,
 973,
 974,
 975,
 976,
 977,
 978,
 979,
 980,
 981,
 982,
 983,
 984,
 985,
 986,
 987,
 988,
 989,
 990,
 991,
 992,
 993,
 994,
 995,
 996,
 997,
 998,
 999,
 ...]

In [3]:
import numpy as np
a = np.arange(100000)
a

array([    0,     1,     2, ..., 99997, 99998, 99999])

In [4]:
%time np.sum(a ** 2) # Numpy is much faster

Wall time: 394 µs

216474736

In [5]:
%time sum([x ** 2 for x in l])

Wall time: 30.3 ms

333328333350000